ALTER TABLE requests
  ADD COLUMN IF NOT EXISTS objet TEXT,
  ADD COLUMN IF NOT EXISTS informations JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS pieces JSONB NOT NULL DEFAULT '[]'::jsonb;
